version: '3.8'

services:
  db:
    image: postgres:15
    container_name: aff_postgres
    environment:
      POSTGRES_DB: aff_db
      POSTGRES_USER: aff_user
      POSTGRES_PASSWORD: aff_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: aff_app
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aff_db
      SPRING_DATASOURCE_USERNAME: aff_user
      SPRING_DATASOURCE_PASSWORD: aff_password
    networks:
      - aff_network

volumes:
  db_data:

networks:
  aff_network:
